/**
 * Centralized user-facing copy for the app.
 * Replace or extend for localization (e.g. i18next) later.
 */
export const strings = {
  app: {
    name: 'iHute',
  },

  tabs: {
    trips: 'Trips',
    activities: 'Activities',
    search: 'Search',
    travels: 'Travels',
    profile: 'Profile',
    dashboard: 'Dashboard',
    report: 'Report',
    publish: 'Publish',
  },

  auth: {
    welcomeBack: 'Welcome back',
    signInContinue: 'Sign in to continue',
    signIn: 'Sign In',
    signingIn: 'Signing in...',
    logOut: 'Log out',
    logOutConfirm: 'Are you sure?',
    email: 'Email',
    password: 'Password',
    verifyCode: 'Verify code',
    completeProfile: 'Complete profile',
    helperAccounts: 'Passenger: passenger@ihute.com | Driver: driver@ihute.com',
    orSignInWith: 'Or sign in with',
    comingSoon: 'Coming soon',
    socialSignInMessage: (provider: string) =>
      `Sign in with ${provider} will be available soon. Use email and password for now.`,
    emailPasswordRequired: 'Email and password are required.',
    enterValidEmail: 'Enter a valid email address.',
    couldNotSignIn: 'Could not sign in. Try again.',
    forgotPassword: 'Forgot password?',
    forgotPasswordSentTitle: 'Check your email',
    forgotPasswordSentSubtitle: (email: string) => `If an account exists for ${email}, we sent a reset link.`,
    forgotPasswordSubtitle: 'Enter your email and we will send you a link to reset your password.',
    sendResetLink: 'Send reset link',
    sending: 'Sending...',
    backToLogin: 'Back to Login',
    resetPassword: 'Reset password',
    resetPasswordSubtitle: 'Enter your new password below.',
    resetPasswordSuccessTitle: 'Password updated',
    resetPasswordSuccessSubtitle: 'You can now sign in with your new password.',
    resetPasswordButton: 'Reset password',
    newPassword: 'New password',
    confirmPassword: 'Confirm password',
    saving: 'Saving...',
  },

  home: {
    greeting: (name: string) => `Hello, ${name}!`,
    tagline: 'Bus, train, carpool: iHute takes you where you want.',
  },

  profile: {
    account: 'Account',
    preferences: 'Preferences',
    appearance: 'Appearance',
    light: 'Light',
    dark: 'Dark',
    support: 'Support',
    app: 'App',
    scanner: 'Scanner',
    openReport: 'Open Report',
    notifications: 'Notifications',
    privacy: 'Privacy',
    hotline: 'Hotline',
    withdrawalMethods: 'Withdrawal methods',
    linkedAccounts: 'Linked accounts',
    viewAllActivities: 'View all activities',
    myVehicles: 'My vehicles',
    driver: 'Driver',
    passenger: 'Passenger',
    agency: 'Agency',
    scannerRole: 'Scanner',
    activitiesWallet: 'Activities wallet',
    quickTotals: 'Quick totals',
    today: 'Today',
    week: 'Week',
    done: 'Done',
    active: 'Active',
    bookings: 'Bookings',
    income: 'Income',
    viewIncome: 'View income',
    hideIncome: 'Hide income',
    notificationsSubtitle: 'Choose which app updates you want to receive.',
    trips: 'Trips',
    tripUpdates: 'Trip updates',
    tripUpdatesDesc: 'Booking confirmations, departure reminders, and ride status.',
    messages: 'Messages',
    messageAlertsDesc: 'Alerts when drivers or passengers send a message.',
    promotions: 'Promotions',
    promotionsDesc: 'Discounts and product announcements.',
    privacySubtitle: 'Security and data controls for your account.',
    accountVisibility: 'Account visibility',
    accountVisibilityDesc: 'Control how your profile appears to other users.',
    dataExport: 'Data export',
    dataExportDesc: 'Download your account data and trip history.',
    deleteAccount: 'Delete account',
    deleteAccountDesc: 'Remove your profile and personal data from this mock app.',
    hotlineNeedHelp: 'Need help?',
    hotlineSubtitle: 'Call our hotline for support',
    hotlineHours: 'Available daily: 06:00 - 22:00',
    hotlineCall: 'Call',
    hotlineOpening: 'Opening dialer...',
    dispute: 'Dispute',
    disputeViaWhatsApp: 'Dispute via WhatsApp',
    reportDisputeViaWhatsApp: 'Report / Dispute via WhatsApp',
    disputeWhatsAppUnavailable: (number: string) =>
      `WhatsApp is not available. Please contact ${number} on WhatsApp manually.`,
    disputeOpenFailed: (number: string) =>
      `Could not open WhatsApp. Please contact ${number} on WhatsApp manually to report a dispute.`,
    linkedAccountsSubtitle: 'Manage how payments are handled in the app.',
    withdrawalSubtitle: 'Link your Mobile Money or bank account to receive payouts from your trips.',
    addPaymentMethod: 'Add payment method',
    saving: 'Saving...',
    save: 'Save',
    exportReady: 'Export ready',
    exportPreparing: 'Preparing export...',
    aboutYou: 'About you',
    personalDetails: 'Personal details',
    vehicle: 'Vehicle',
    ratingsAndReviews: 'Ratings & Reviews',
    viewPublicProfile: 'View public profile',
    notificationSettings: 'Notification settings',
    passwordAndSecurity: 'Password & Security',
    changePhoto: 'Change photo',
    miniBio: 'Mini bio',
    saveChanges: 'Save Changes',
    updateVehicle: 'Update Vehicle',
    addVehiclePhoto: 'Add vehicle photo',
    savePreferences: 'Save Preferences',
    ridePreferences: 'Ride preferences',
    editProfile: 'Edit profile',
  },

  nav: {
    ticketDetails: 'Ticket details',
    scanTicket: 'Scan ticket',
    notifications: 'Notifications',
    linkedAccounts: 'Linked accounts',
    withdrawalMethods: 'Withdrawal methods',
    privacy: 'Privacy',
    passengerActivities: 'Passenger Activities',
    driverActivities: 'Driver Activities',
    activities: 'Activities',
    allActivities: 'All Activities',
    paymentMethods: 'Payment methods',
    addCard: 'Add card',
    addMobileMoney: 'Add Mobile Money',
    wallet: 'Wallet',
    termsOfService: 'Terms of Service',
    addVehicle: 'Add vehicle',
    editVehicle: 'Edit vehicle',
    earnings: 'Earnings',
    faq: 'FAQ',
    about: 'About',
  },

  common: {
    ok: 'OK',
    cancel: 'Cancel',
    guest: 'Guest',
  },
} as const;
